better error handling

diff --git a/usr/local/bin/flek3s-setup b/usr/local/bin/flek3s-setup
--- a/usr/local/bin/flek3s-setup
+++ b/usr/local/bin/flek3s-setup
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-function sayerror() { echo "[ ERROR ]"; exit 1; }
+function sayerror() { echo "[ ERROR ]"; /usr/local/bin/pause; exit 1; }
 
 function sayok() { echo "[ OK ]"; }
 
@@ -54,14 +54,16 @@ if [ $k3s_installed -eq 1 ]; then
 	if [ $k3s_nodes -eq 1 ]; then 
 		echo "Upgrading single K3s node..."
 		cp /usr/libexec/k3s/k3s /usr/local/bin/k3s && sayok || sayerror
-                INSTALL_K3S_SKIP_DOWNLOAD=true sudo /usr/libexec/k3s/install.sh --write-kubeconfig-mode 644 --no-deploy traefik && sayok || sayerror
+                export INSTALL_K3S_SKIP_DOWNLOAD=true 
+		export PATH=/sbin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
+		/bin/bash -c '/usr/libexec/k3s/install.sh --write-kubeconfig-mode 644 --no-deploy traefik' && sayok || sayerror
 		echo "Restarting K3s..."
-		sudo /etc/init.d/k3s restart && sayok || sayerror
+		/etc/init.d/k3s restart && sayok || sayerror
 		/usr/local/bin/pause
 		
 	elif [ $k3s_nodes -gt 1 ]; then
 		echo "[ INFO ] Upgrading multi-node cluster"
-		sudo /usr/libexec/k3s/k3s-deploy-multi --upgrade true && sayok || sayerror
+		/usr/libexec/k3s/k3s-deploy-multi --upgrade true && sayok || sayerror
 		/usr/local/bin/pause
 	else
 		echo "[ ERROR ] Unsupported cluster detected. Has $k3s_nodes nodes."
@@ -80,13 +82,15 @@ else
 	# if one node, install single node K3s
 		echo "Installing single K3s node..."
 		cp /usr/libexec/k3s/k3s /usr/local/bin/k3s && sayok || sayerror
-  		INSTALL_K3S_SKIP_DOWNLOAD=true sudo /bin/bash /usr/libexec/k3s/install.sh --write-kubeconfig-mode 644 --no-deploy traefik && sayok || sayerror
+		export PATH=/sbin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
+  		export INSTALL_K3S_SKIP_DOWNLOAD=true 
+		/bin/bash -c '/usr/libexec/k3s/install.sh --write-kubeconfig-mode 644 --no-deploy traefik' && sayok || sayerror
 		/etc/init.d/k3s start && sayok || sayerror
 		/usr/local/bin/pause
 	elif [ $newnodes -eq 3 ]; then 
 	# if 3 node, install 3 node K3s
 		echo "Installing multi node K3s..."
-		sudo /usr/libexec/flek3s/k3s-deploy-multi && sayok || sayerror
+		/usr/libexec/flek3s/k3s-deploy-multi && sayok || sayerror
 		/usr/local/bin/pause
 	fi
 fi
