added some better logic for multinode deployment

diff --git a/usr/libexec/flek3s/flek3s-deploy-multi b/usr/libexec/flek3s/flek3s-deploy-multi
--- a/usr/libexec/flek3s/flek3s-deploy-multi
+++ b/usr/libexec/flek3s/flek3s-deploy-multi
@@ -1,6 +1,5 @@
 #!/bin/bash
 
-longhorn_version=1.2.2
 run_dir=$(dirname "$BASH_SOURCE")
 echo "run_dir = $run_dir"
 upgrade="false"
@@ -39,6 +38,39 @@ function usage {
     echo "  --upgrade			Flag if performing an upgrade"
 }
 
+# Safety checks. 
+# Is Kubernetes already running? Are we running K3s? Is it single node? 
+# We should only run this if there is NO existing Kubernetes OR if we have confirmed 
+# that the existing Kubernetes is a single node K3s cluster
+
+has_kubectl=$(which kubectl >/dev/null 2>&1 && echo true || echo false)
+if [ "$has_kubectl" == "true" ]; then
+	echo "[ INFO ] kubectl detected. Checking if we're on K3s."	
+	has_k3s=$(which k3s >/dev/null 2>&1 && echo true || echo false)
+	if [ "$has_k3s" == "true" ]; then 
+		echo "[ INFO ] K3s detected. Checking for an existing cluster."
+		k3s_nodes=$(k3s kubectl get nodes | head -n -1 | wc -l)
+		if [ $k3s_nodes -eq 3 ]; then 
+			echo "[ OK ] 3 node K3s cluster detected, proceeding with K3s cluster upgrade." 
+			upgrade="true"
+		elif [ $k3s_nodes -eq 1 ]; then 
+			echo "[ ERROR ] Single node cluster detected. Please use the single node infrastructure-deploy script."
+			exit 1
+		else
+			echo "[ ERROR ] This cluster has $k3s_nodes nodes. Unable to continue."
+			exit 1
+		fi
+	else 
+		echo "[ ERROR ] Non-K3s Kubernetes cluster detected."
+		exit 1
+	
+	fi
+else
+	echo "[ INFO ] No Kubernetes found. Starting multi-node K3s install."
+fi
+
+# If we have not exited yet, we can proceed with taking action to install or upgrade K3s
+
 # Handle our switches
 while [[ ${1} ]]; do
     case "${1}" in
@@ -59,11 +91,25 @@ done
 
 # If this is an existing cluster, we should use the existing config, else get new info
 if [ "$upgrade" == "true" ]; then 
-	nodes_json=$(kubectl get nodes -o json | jq [.items[].metadata.annotations])
-	node0_ip=$(echo $nodes_json | jq -r '.[0] | with_entries(select(.key|match("public-ip";"i")))[]')
-	node1_ip=$(echo $nodes_json | jq -r '.[1] | with_entries(select(.key|match("public-ip";"i")))[]')
-	node2_ip=$(echo $nodes_json | jq -r '.[2] | with_entries(select(.key|match("public-ip";"i")))[]')
-
+	if [ -f "/usr/local/bin/etcd_cluster_members" ]; then 
+		etcd_node_ips=$(/usr/local/bin/etcd_cluster_members | grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])' | sort | uniq)
+		nodeid=0;
+		for nodeip in $etcd_node_ips; do 
+			echo "Node${nodeid} IP is $nodeip"
+			declare node${nodeid}_ip=$nodeip
+			nodeid=$((nodeid+1))
+		done
+	else
+		echo "[ WARNING ] Could not pull IPS from etcd cluster. Please re-enter manually"
+		for nodeid in 0 1 2; do 
+			valid=100
+			while [ "$valid" != "0" ]; do
+				read -p "IP Address for Node${nodeid}> " node_ip
+				valid=$(validate_ip $node_ip)
+				declare node${nodeid}_ip=$node_ip
+			done
+		done
+	fi
 else
 	# Get our connection information
 	for nodeid in 0 1 2; do 
@@ -95,7 +141,6 @@ for nodeid in 0 1 2; do
 	valid=100
 	while [ "$valid" != "0" ]; do
 		echo ""
-#		read -p "Username for Node${nodeid} ($(eval echo \$node${nodeid}_ip)) SSH user> " node_user
 		node_user=peer
 		ssh-keyscan -H $(eval echo \$node${nodeid}_ip) >> ~/.ssh/known_hosts 2>/dev/null
 		existing_trust=$( ssh -o PasswordAuthentication=no  -o BatchMode=yes ${node_user}@$(eval echo \$node${nodeid}_ip) exit &>/dev/null && echo true || echo false )
@@ -181,7 +226,7 @@ EOF
 
 cat > ca-csr.json << EOF2
 {
-    "CN": "Pliant.io temp CA",
+    "CN": "flek3s temp CA",
     "key": {
         "algo": "rsa",
         "size": 2048
@@ -190,7 +235,7 @@ cat > ca-csr.json << EOF2
         {
             "C": "US",
             "L": "CA",
-            "O": "Pliant.io",
+            "O": "flek3s",
             "ST": "Delaware",
             "OU": "Development",
             "OU": "Testing"
@@ -301,6 +346,8 @@ echo""
 echo "+++ ETCD Cluster: $cluster"
 echo "+++ ETCD Endpoints: $endpoints"
 echo""
+echo "/usr/local/bin/etcdctl --endpoints ${endpoints} --cacert /var/lib/etcd/cfssl/ca.pem --cert /var/lib/etcd/cfssl/client.pem --key /var/lib/etcd/cfssl/client-key.pem member list" > etcd_cluster_members
+echo "/usr/local/bin/etcdctl --endpoints ${endpoints} --cacert /var/lib/etcd/cfssl/ca.pem --cert /var/lib/etcd/cfssl/client.pem --key /var/lib/etcd/cfssl/client-key.pem endpoint health" > etcd_cluster_health
 
 
 for nodeid in 0 1 2; do 
@@ -467,13 +514,17 @@ force-new-cluster: false
 auto-compaction-mode: periodic
 auto-compaction-retention: "1"
 EOF11
-		scp etcd.conf.yml ${user}@${ip}:
-		ssh ${user}@${ip} sudo mv etcd.conf.yml /etc/etcd/conf.yml && sayok || sayerr
-		ssh ${user}@${ip} sudo chown -R etcd:etcd /var/lib/etcd/ && sayok || sayerr
-		ssh ${user}@${ip} sudo rc-update add etcd default && sayok || sayerr
-		ssh ${user}@${ip} sudo /etc/init.d/etcd start && sayok || sayerr
-		echo "sudo /usr/bin/etcdctl --endpoints ${endpoints} --cacert /var/lib/etcd/cfssl/ca.pem --cert /var/lib/etcd/cfssl/client.pem --key /var/lib/etcd/cfssl/client-key.pem member list" | ssh ${user}@${ip} sudo tee /usr/local/bin/etcd-members
-		echo "sudo /usr/bin/etcdctl --endpoints ${endpoints}  --cacert /var/lib/etcd/cfssl/ca.pem --cert /var/lib/etcd/cfssl/client.pem --key /var/lib/etcd/cfssl/client-key.pem endpoint health" | ssh ${user}@${ip} sudo tee /usr/local/bin/etcd-health
+	scp etcd.conf.yml ${user}@${ip}:
+	ssh ${user}@${ip} sudo mv etcd.conf.yml /etc/etcd/conf.yml && sayok || sayerr
+	ssh ${user}@${ip} sudo chown -R etcd:etcd /var/lib/etcd/ && sayok || sayerr
+	ssh ${user}@${ip} sudo rc-update add etcd default && sayok || sayerr
+	ssh ${user}@${ip} sudo /etc/init.d/etcd start && sayok || sayerr
+	scp etcd_cluster_members ${user}@${ip}:
+	ssh ${user}@${ip} sudo chmod +x etcd_cluster_members
+	ssh ${user}@${ip} sudo mv etcd_cluster_members /usr/local/bin/
+	scp etcd_cluster_health ${user}@${ip}:
+	ssh ${user}@${ip} sudo chmod +x etcd_cluster_health
+	ssh ${user}@${ip} sudo mv etcd_cluster_health /usr/local/bin/
 done
 
 echo""
@@ -482,11 +533,11 @@ sleep 30
 
 echo ""
 echo ">>> Checking ETCD Cluster Members"
-sudo /usr/bin/etcdctl --endpoints ${endpoints} --cacert /var/lib/etcd/cfssl/ca.pem --cert /var/lib/etcd/cfssl/client.pem --key /var/lib/etcd/cfssl/client-key.pem member list && sayok || sayerr
+/usr/local/bin/etcd_cluster_members && sayok || sayerr
 
 echo ""
 echo ">>> Checking ETCD Cluster Health"
-sudo /usr/bin/etcdctl --endpoints ${endpoints}  --cacert /var/lib/etcd/cfssl/ca.pem --cert /var/lib/etcd/cfssl/client.pem --key /var/lib/etcd/cfssl/client-key.pem endpoint health && sayok || sayerr
+/usr/local/bin/etcd_cluster_health && sayok || sayerr
 echo ""
 
 ############
